FROM node:18-alpine

WORKDIR /app/frontend

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy app
COPY frontend . 

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
